cargo-features = ["edition2021"]

[package]
name = "tokey"
version = "0.1.0"
edition = "2021"

[features]
test-bpf = []

[dependencies]
solana-program = "*"

[dev-dependencies]

[lib]
crate-type = ["cdylib", "lib"]
